import { Prisma } from '@prisma/client'
import slugify from 'slugify'

const skillData: { name: string; slug?: string }[] = [
  { name: 'Vue JS' },
  { name: 'React JS' },
  { name: 'Angular' },
  { name: 'Node js' },
  { name: 'Express js' },
  { name: 'Django' },
  { name: 'Flask' },
  { name: 'Svelte' },
  { name: 'Nextjs' },
  { name: 'Redux' },
  { name: 'GraphQL' },
  { name: 'MongoDB' },
  { name: 'TypeScript' },
  { name: 'Java' },
  { name: 'Python' },
  { name: 'Ruby' },
  { name: 'C Sharp' },
  { name: 'PHP' },
  { name: 'Go' },
  { name: 'Rust' },
  { name: 'Graphic Design' },
  { name: 'Video Editing' },
  { name: 'Photography' },
  { name: 'Content Writing' },
  { name: 'Marketing Strategy' },
  { name: 'Project Management' },
  { name: 'UIUX Design' },
  { name: 'Customer Service' },
  { name: 'Data Analysis' },
  { name: 'Digital Marketing' },
  { name: 'Social Media Management' },
  { name: 'Public Speaking' },
  { name: 'Event Planning' },
  { name: 'Time Management' },
  { name: 'Leadership' },
  { name: 'Negotiation Skills' },
  { name: 'Financial Literacy' },
  { name: 'Languages' },
  { name: 'Health and Wellness' },
  { name: 'Creative Writing' },
  { name: 'Problem Solving' },
  { name: 'Critical Thinking' },
  { name: 'Emotional Intelligence' },
  { name: 'Cooking' },
  { name: 'Networking' },
  { name: 'Foreign Languages' },
  { name: 'Illustration' },
  { name: 'Video Production' },
  { name: 'Ecommerce' },
  { name: 'Mindfulness' },
  { name: 'Culinary Arts' },
  { name: 'Interior Design' },
  { name: 'Public Relations' },
  { name: 'Investing' },
  { name: 'Mobile App Development' },
  { name: 'Robotics' },
  { name: 'Conflict Resolution' },
  { name: 'Creative Problem Solving' },
  { name: 'Artificial Intelligence' },
  { name: 'Cybersecurity' },
  { name: 'Digital Illustration' },
  { name: 'Agile Methodology' },
  { name: 'Virtual Reality' },
  { name: 'Robotics Process Automation' },
  { name: 'Financial Planning' },
  { name: 'Machine Learning' },
  { name: 'Digital Marketing Analytics' },
  { name: 'Drawing and Sketching' },
  { name: 'Search Engine Optimization' },
  { name: 'Game Development' },
  { name: 'Customer Relationship Management' },
  { name: 'Cryptocurrency and Blockchain' },
  { name: 'User Interface UI Design' },
  { name: 'Remote Collaboration' },
  { name: 'Data Visualization' },
  { name: 'Augmented Reality' },
  { name: 'Sales Strategy' },
  { name: 'Copywriting' },
  { name: 'Artificial Neural Networks' },
  { name: 'Network Security' },
  { name: 'Content Strategy' },
  { name: 'Creative Coding' },
  { name: 'Network Administration' },
  { name: 'Time Tracking' },
  { name: 'Innovation Management' },
  { name: 'Natural Language Processing' },
  { name: 'Project Planning' },
  { name: 'Knowledge Management' },
  { name: 'Investment Strategy' },
  { name: 'Virtual Collaboration' },
  { name: 'Machine Vision' },
]

skillData.forEach((skill) => {
  skill.slug = slugify(skill.name, {
    lower: true,
  })
})

export default skillData
